from __future__ import annotations

import argparse
import json
from pathlib import Path


def _parse_seeds(text: str) -> list[int]:
    seeds = [int(x.strip()) for x in text.split(",") if x.strip()]
    if not seeds:
        raise ValueError("at least one seed is required")
    if len(set(seeds)) != len(seeds):
        raise ValueError(f"duplicate seeds are not allowed: {seeds}")
    return seeds


def _quote(value: str) -> str:
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Create reproducible train/infer command files for independent seeded runs."
    )
    ap.add_argument("--train_glob", required=True)
    ap.add_argument("--test_glob", required=True)
    ap.add_argument("--out_dir", required=True)
    ap.add_argument("--seeds", default="7,13,23")
    ap.add_argument("--device", default="cuda")
    ap.add_argument("--steps", type=int, default=0)
    ap.add_argument("--warmup", type=int, default=1500)
    ap.add_argument("--kmax_final", type=int, default=-1)
    ap.add_argument("--sequence_policy", default="rebuild")
    ap.add_argument("--max_tokens", type=int, default=128)
    ap.add_argument("--beam_width", type=int, default=1)
    ap.add_argument("--beam_topk", type=int, default=16)
    ap.add_argument("--layout_preset", default="checkpoint")
    args = ap.parse_args()

    seeds = _parse_seeds(args.seeds)
    out = Path(args.out_dir).expanduser().resolve()
    out.mkdir(parents=True, exist_ok=True)

    manifest: dict[str, object] = {
        "train_glob": args.train_glob,
        "test_glob": args.test_glob,
        "seeds": seeds,
        "runs": [],
    }
    ps_lines = [
        "$ErrorActionPreference = 'Stop'",
        "# Generated by scripts/plan_seeded_runs.py. Run commands one by one, or run this file directly.",
        "",
    ]

    for seed in seeds:
        run_dir = out / f"seed_{seed}"
        ckpt = run_dir / "model.pt"
        infer_dir = run_dir / "infer"
        train_cmd = [
            "python",
            "scripts/step3_train_masked.py",
            "--train_glob",
            args.train_glob,
            "--save_path",
            str(ckpt),
            "--seed",
            str(seed),
            "--device",
            args.device,
            "--steps",
            str(args.steps),
            "--warmup",
            str(args.warmup),
            "--kmax_final",
            str(args.kmax_final),
            "--sequence_policy",
            args.sequence_policy,
            "--max_tokens",
            str(args.max_tokens),
        ]
        infer_cmd = [
            "python",
            "scripts/step4_infer.py",
            "--test_glob",
            args.test_glob,
            "--ckpt",
            str(ckpt),
            "--out_dir",
            str(infer_dir),
            "--device",
            args.device,
            "--beam_width",
            str(args.beam_width),
            "--beam_topk",
            str(args.beam_topk),
            "--layout_preset",
            args.layout_preset,
        ]
        manifest["runs"].append(
            {
                "seed": seed,
                "run_dir": str(run_dir),
                "checkpoint": str(ckpt),
                "infer_dir": str(infer_dir),
                "train_cmd": train_cmd,
                "infer_cmd": infer_cmd,
            }
        )
        ps_lines.extend(
            [
                f"New-Item -ItemType Directory -Force -Path {_quote(str(run_dir))} | Out-Null",
                " ".join(_quote(x) if any(ch.isspace() for ch in x) else x for x in train_cmd),
                " ".join(_quote(x) if any(ch.isspace() for ch in x) else x for x in infer_cmd),
                "",
            ]
        )

    summarize_cmd = [
        "python",
        "scripts/summarize_seeded_infer.py",
        "--runs_dir",
        str(out),
        "--seeds",
        ",".join(str(s) for s in seeds),
        "--out_json",
        str(out / "summary_mean_std.json"),
        "--out_csv",
        str(out / "summary_mean_std.csv"),
    ]
    ps_lines.append(" ".join(_quote(x) if any(ch.isspace() for ch in x) else x for x in summarize_cmd))

    manifest_path = out / "seeded_runs_manifest.json"
    commands_path = out / "run_seeded_experiments.ps1"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    commands_path.write_text("\n".join(ps_lines) + "\n", encoding="utf-8")
    print(f"wrote {manifest_path}")
    print(f"wrote {commands_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
