"""Decision Transformer RL-style online fine-tuning on clean trajectories (paper-aligned).

This version moves from pure supervised training to an RL-style loop closer to the paper:
- Generate trajectories with current policy (Algorithm 1 style)
- Keep only those satisfying hard constraints (boundary, overlap, spacing)
- Compute score = λ1·1/HPWL + λ2·NSLW
- Prioritized replay: sample by ω(τ) = exp(score/α) / E_B[exp(score/α)]
- Update policy via L(θ) = − E_B[ ω(τ) · log π_θ(a_t | τ_t) ]

Notes:
- We reuse ExpertTrajectoryDataset to provide task info and helpers, but actions fed to the
    model are generated by the current policy, not supervised labels.
- Returns-to-go are computed from rewards r_t = HPWL_{t-1} − HPWL_{t-2} within the rollout.
"""
from pathlib import Path
from typing import List, Tuple, Dict, Any, Optional

import math
import numpy as np
import torch
import torch.nn.functional as F
from torch import nn
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from tqdm import tqdm

from datasets.expert_dataset import ExpertTrajectoryDataset, ExpertTrajectoryProcessor
from DT.models.dt_model import DecisionTransformer
from reward_utils import (
    DEFAULT_SLW_PENALTY_WEIGHT,
    returns_from_rewards,
    step_reward,
    trajectory_score,
)

# --------------------
# Utility: Hard constraints check (boundary, overlap, spacing)
# --------------------
def satisfies_hard_constraints(processor, placement_sequence: List[Dict[str, Any]], grid_size: int, margin: int) -> bool:
    """
    Basic legality check:
    - components must be within boundary (0..grid_size)
    - no overlap between placed components (consider rotated size)
    - spacing >= rule-derived requirement (grid units)
    placement_sequence: list of dict with keys: comp_id, x, y, rot, w, h
    """
    # boundary check
    for comp in placement_sequence:
        w, h = comp['w'], comp['h']
        rot = comp['rot']
        if rot % 2 == 1:
            w, h = h, w
        x, y = comp['x'], comp['y']
        if x < 0 or y < 0 or x + w > grid_size or y + h > grid_size:
            return False

    # overlap + spacing check (AABB with margin)
    def aabb(x, y, w, h):
        return (x, y, x + w, y + h)

    def expanded(box, m):
        x1, y1, x2, y2 = box
        return (x1 - m, y1 - m, x2 + m, y2 + m)

    boxes = []
    comp_type_lookup = {}
    if hasattr(processor, "component_list"):
        for comp in processor.component_list:
            comp_type_lookup[comp["comp_id"]] = comp.get("type_id", 0)

    body_rules = getattr(processor, "body_spacing_rules", {}) or {}

    def spacing_requirement(comp_id_a: int, comp_id_b: int) -> int:
        type_a = comp_type_lookup.get(comp_id_a)
        type_b = comp_type_lookup.get(comp_id_b)
        if type_a is not None and type_b is not None:
            if (type_a, type_b) in body_rules:
                return int(body_rules[(type_a, type_b)])
            if (type_b, type_a) in body_rules:
                return int(body_rules[(type_b, type_a)])
        return margin

    for comp in placement_sequence:
        w, h = comp['w'], comp['h']
        rot = comp['rot']
        if rot % 2 == 1:
            w, h = h, w
        boxes.append((comp['comp_id'], aabb(comp['x'], comp['y'], w, h)))

    for i in range(len(boxes)):
        for j in range(i + 1, len(boxes)):
            comp_id_i, bi = boxes[i]
            comp_id_j, bj = boxes[j]
            # overlap check
            if not (bi[2] <= bj[0] or bj[2] <= bi[0] or bi[3] <= bj[1] or bj[3] <= bi[1]):
                return False
            requirement = spacing_requirement(comp_id_i, comp_id_j)
            if requirement <= 0:
                continue

            ei = expanded(bi, requirement)
            ej = expanded(bj, requirement)
            if not (ei[2] <= ej[0] or ej[2] <= ei[0] or ei[3] <= ej[1] or ej[3] <= ei[1]):
                dx = 0.0
                if bi[2] < bj[0]:
                    dx = bj[0] - bi[2]
                elif bj[2] < bi[0]:
                    dx = bi[0] - bj[2]

                dy = 0.0
                if bi[3] < bj[1]:
                    dy = bj[1] - bi[3]
                elif bj[3] < bi[1]:
                    dy = bi[1] - bj[3]

                if dx == 0.0 and dy == 0.0:
                    distance = 0.0
                elif dx == 0.0:
                    distance = dy
                elif dy == 0.0:
                    distance = dx
                else:
                    distance = math.hypot(dx, dy)

                if distance < requirement:
                    return False
    return True

# --------------------
# Trajectory utilities
# --------------------
def prioritized_weights(scores: List[float], alpha: float) -> List[float]:
    import math
    if not scores:
        return []
    if abs(alpha) < 1e-9:
        return [1.0 for _ in scores]

    max_score = max(scores)
    exps = []
    for s in scores:
        exponent = (s - max_score) / alpha
        exponent = max(min(exponent, 700.0), -700.0)
        exps.append(math.exp(exponent))

    mean = sum(exps) / len(exps)
    if mean <= 0:
        return [1.0 for _ in exps]
    return [e / mean for e in exps]


def _draw_board(component_boxes: List[Tuple[int,int,int,int,int]], grid_size: int, title: str, out_path: Path):
    """component_boxes: list of (x, y, w, h, rot)."""
    fig, ax = plt.subplots(figsize=(6,6))
    ax.set_title(title)
    ax.set_xlim(0, grid_size)
    ax.set_ylim(0, grid_size)
    ax.set_aspect('equal')
    ax.invert_yaxis()
    for (x,y,w,h,rot) in component_boxes:
        rect = Rectangle((x,y), w, h, linewidth=0.6, edgecolor='C0', facecolor='none')
        ax.add_patch(rect)
        ax.text(x+ w/2, y+ h/2, f"r{rot}", fontsize=6, ha='center', va='center')
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(out_path)
    plt.close(fig)


def load_clean_trajectory_list(filepath: str) -> List[str]:
    """Load list of clean trajectory names from file."""
    with open(filepath, 'r') as f:
        return [line.strip() for line in f if line.strip()]


def collect_samples(dataset: ExpertTrajectoryDataset, max_samples: int) -> List:
    samples = []
    print(f"Collecting up to {max_samples} samples from {len(dataset)} trajectories...")

    for idx in tqdm(range(min(len(dataset), max_samples)), desc="Collecting samples"):
        try:
            samples.append(dataset[idx])
        except Exception as e:
            print(f"[skip] index={idx} error={e}")
    return samples


def batchify(samples: List, batch_size: int):
    for i in range(0, len(samples), batch_size):
        yield samples[i:i + batch_size]


def ensure_legal_action(obs: Dict[str, Any], action: Tuple[int, int, int]) -> Tuple[int, int, int]:
    """Project model action onto the nearest legal placement defined by position_mask."""
    x, y, rot = map(int, action)
    position_mask = obs.get("position_mask")
    if position_mask is None:
        return (max(x, 0), max(y, 0), max(rot, 0))

    num_rot, height, width = position_mask.shape

    def valid(ax: int, ay: int, arot: int) -> bool:
        return (
            0 <= arot < num_rot and
            0 <= ay < height and
            0 <= ax < width and
            position_mask[arot, ay, ax] == 0
        )

    if valid(x, y, rot):
        return (x, y, rot)

    best_candidate = None
    best_distance = None
    for rot_idx in range(num_rot):
        legal_positions = np.argwhere(position_mask[rot_idx] == 0)
        if legal_positions.size == 0:
            continue
        distances = np.abs(legal_positions[:, 0] - y) + np.abs(legal_positions[:, 1] - x)
        min_idx = int(np.argmin(distances))
        candidate_y, candidate_x = legal_positions[min_idx]
        distance = float(distances[min_idx])
        if best_candidate is None or distance < best_distance:
            best_candidate = (int(candidate_x), int(candidate_y), int(rot_idx))
            best_distance = distance

    if best_candidate is not None:
        return best_candidate
    return (0, 0, 0)


def rollout_policy(
    model: DecisionTransformer,
    processor: ExpertTrajectoryProcessor,
    lambda1: float,
    lambda2: float,
    device: torch.device,
    target_return: float = 0.0,
    hpwl_threshold: float | None = None,
    bonus_value: float = -0.01,
    slw_penalty_weight: float = DEFAULT_SLW_PENALTY_WEIGHT,
    deterministic: bool = False,
) -> Optional[Dict[str, Any]]:
    """Generate a trajectory by rolling out the current policy inside the PCB env."""

    env = processor.build_env()
    reset_result = env.reset()
    obs = reset_result[0] if isinstance(reset_result, tuple) else reset_result
    hi_features = torch.from_numpy(processor._compute_hi_features()).to(device)

    states_history: List[torch.Tensor] = []
    actions_history: List[torch.Tensor] = []
    returns_history: List[torch.Tensor] = []
    timesteps_history: List[int] = []

    traj_states: List[torch.Tensor] = []
    traj_actions: List[torch.Tensor] = []
    traj_rewards: List[float] = []
    hpwls: List[float] = []
    slws: List[float] = []
    nslws: List[float] = []

    rtg_remaining = float(target_return)
    step_idx = 0
    prev_hpwl = float(getattr(env, "hpwl", 0.0))
    prev_slw = float(getattr(env, "slw", 0.0))

    while True:
        state_tensor = processor._build_state_tensor(obs, rotation=None).to(dtype=torch.float32)
        states_history.append(state_tensor)

        if len(actions_history) < len(states_history):
            actions_history.append(torch.zeros(3, dtype=torch.long))
        if len(returns_history) < len(states_history):
            returns_history.append(torch.tensor([rtg_remaining], dtype=torch.float32))
        if len(timesteps_history) < len(states_history):
            timesteps_history.append(step_idx)

        states_seq = torch.stack(states_history, dim=0).to(device)
        actions_seq = torch.stack(actions_history, dim=0).to(device)
        returns_seq = torch.stack(returns_history, dim=0).to(device)
        timesteps_seq = torch.tensor(timesteps_history, dtype=torch.long, device=device)

        action = model.get_action(
            states=states_seq,
            actions=actions_seq,
            rewards=None,
            returns_to_go=returns_seq,
            timesteps=timesteps_seq,
            deterministic=deterministic,
            hpwl_threshold=hpwl_threshold,
            bonus_value=bonus_value,
            hi=hi_features.unsqueeze(0),
        )

        action = ensure_legal_action(obs, action)
        actions_history[-1] = torch.tensor(action, dtype=torch.long)

        step_result = env.step(action)
        if len(step_result) == 5:
            obs_next, reward, terminated, truncated, info = step_result
            done = bool(terminated or truncated)
        else:
            obs_next, reward, done, info = step_result

        traj_states.append(state_tensor.clone())
        traj_actions.append(torch.tensor(action, dtype=torch.long))

        hpwl_val = float(info.get("hpwl", getattr(env, "hpwl", 0.0))) if isinstance(info, dict) else float(getattr(env, "hpwl", 0.0))
        slw_val = float(info.get("slw", getattr(env, "slw", 0.0))) if isinstance(info, dict) else float(getattr(env, "slw", 0.0))
        hpwls.append(hpwl_val)
        slws.append(slw_val)
        nslw_val = float(info.get("nslw", 1.0 / (1.0 + max(slw_val, 1e-6)))) if isinstance(info, dict) else 1.0 / (1.0 + max(slw_val, 1e-6))
        nslws.append(nslw_val)

        reward_step = step_reward(
            prev_hpwl=prev_hpwl,
            curr_hpwl=hpwl_val,
            prev_slw=prev_slw,
            curr_slw=slw_val,
            hpwl_threshold=hpwl_threshold,
            slw_penalty_weight=slw_penalty_weight,
        )
        traj_rewards.append(reward_step)

        rtg_remaining -= reward_step
        if len(returns_history) > 0:
            returns_history[-1] = torch.tensor([rtg_remaining], dtype=torch.float32)

        prev_hpwl = hpwl_val
        prev_slw = slw_val
        obs = obs_next
        step_idx += 1

        if done or step_idx >= getattr(env, "num_components", len(traj_states) + 1):
            break

    if not traj_states:
        return None

    states_tensor = torch.stack(traj_states, dim=0)
    actions_tensor = torch.stack(traj_actions, dim=0)
    rewards_tensor = torch.tensor(traj_rewards, dtype=torch.float32).unsqueeze(-1)

    returns_values = returns_from_rewards(traj_rewards)
    returns_tensor = torch.tensor(returns_values, dtype=torch.float32).unsqueeze(-1)

    timesteps_tensor = torch.arange(len(traj_rewards), dtype=torch.long)
    attention_mask = torch.ones(len(traj_rewards), dtype=torch.long)

    hpwl_tensor = torch.tensor(hpwls, dtype=torch.float32).unsqueeze(-1)
    slw_tensor = torch.tensor(slws, dtype=torch.float32).unsqueeze(-1)
    nslw_tensor = torch.tensor(nslws, dtype=torch.float32).unsqueeze(-1)

    hpwl_final = hpwls[-1] if hpwls else 1.0
    nslw_final = nslws[-1] if nslws else 0.0
    score = trajectory_score(lambda1, lambda2, hpwl_final=hpwl_final, nslw_final=nslw_final)

    placement_sequence = []
    for (px, py, pw, ph, _type_id, comp_id), action_tensor in zip(env.placed_components, traj_actions):
        placement_sequence.append({
            "comp_id": int(comp_id),
            "x": int(px),
            "y": int(py),
            "rot": int(action_tensor[2].item()),
            "w": int(pw),
            "h": int(ph),
        })

    return {
        "states": states_tensor.cpu(),
        "actions": actions_tensor.cpu(),
        "rewards": rewards_tensor.cpu(),
        "returns_to_go": returns_tensor.cpu(),
        "timesteps": timesteps_tensor.cpu(),
        "attention_mask": attention_mask.cpu(),
        "hpwl": hpwl_tensor.cpu(),
        "slw": slw_tensor.cpu(),
        "nslw": nslw_tensor.cpu(),
        "score": score,
        "episode_reward": float(sum(traj_rewards)),
        "hpwl_final": hpwl_final,
        "nslw_final": nslw_final,
        "placement_sequence": placement_sequence,
        "hi": hi_features.cpu(),
    }


def build_training_batch(entries: List[Dict[str, Any]], weights: List[float]) -> Dict[str, torch.Tensor]:
    """Pad variable-length trajectories from replay buffer into batch tensors."""

    states = torch.nn.utils.rnn.pad_sequence([e["states"] for e in entries], batch_first=True)
    actions = torch.nn.utils.rnn.pad_sequence([e["actions"] for e in entries], batch_first=True)
    returns = torch.nn.utils.rnn.pad_sequence([e["returns_to_go"] for e in entries], batch_first=True)
    timesteps = torch.nn.utils.rnn.pad_sequence([e["timesteps"] for e in entries], batch_first=True)
    attention = torch.nn.utils.rnn.pad_sequence([e["attention_mask"] for e in entries], batch_first=True)
    hi = torch.stack([e["hi"] for e in entries], dim=0)

    batch = {
        "states": states,
        "actions": actions,
        "returns_to_go": returns,
        "timesteps": timesteps,
        "attention_mask": attention,
        "weights": torch.tensor(weights, dtype=torch.float32),
        "hi": hi,
    }
    return batch


def policy_loss_from_buffer(batch, model: DecisionTransformer, device: torch.device):
    """Compute L(θ) = − E_B[ ω · log π(a_t | τ_t) ] over sampled trajectories.
    batch keys: states, actions, returns_to_go, timesteps, attention_mask, weights (B,)
    """
    states = batch["states"].to(device)            # (B, T, 4, N, N)
    actions = batch["actions"].to(device)          # (B, T, 3)
    returns_to_go = batch["returns_to_go"].to(device)
    timesteps = batch["timesteps"].to(device)
    attention_mask = batch["attention_mask"].to(device)
    weights = batch["weights"].to(device)          # (B,)
    hi = batch["hi"].to(device)

    # Forward to get action logits
    _, action_preds, _ = model(
        states=states,
        actions=actions,
        rewards=None,
        returns_to_go=returns_to_go,
        timesteps=timesteps,
    attention_mask=attention_mask,
    hi=hi,
    )
    x_logits, y_logits, rot_logits = action_preds

    # Convert logits to log-probs
    x_logp = torch.log_softmax(x_logits, dim=-1)
    y_logp = torch.log_softmax(y_logits, dim=-1)
    rot_logp = torch.log_softmax(rot_logits, dim=-1)

    x_targets = actions[:, :, 0]
    y_targets = actions[:, :, 1]
    rot_targets = actions[:, :, 2]

    mask = attention_mask.bool()  # (B, T)

    # Gather log-probs for taken actions
    def gather_logp(logp: torch.Tensor, targets: torch.Tensor):
        # logp: (B, T, C), targets: (B, T)
        B, T, C = logp.shape
        logp_flat = logp.view(B * T, C)
        idx_flat = targets.view(B * T)
        chosen = logp_flat[torch.arange(B * T, device=logp.device), idx_flat]
        return chosen.view(B, T)

    x_lp = gather_logp(x_logp, x_targets)
    y_lp = gather_logp(y_logp, y_targets)
    rot_lp = gather_logp(rot_logp, rot_targets)

    # Sum log-probs across (x,y,rot) per timestep
    step_logp = x_lp + y_lp + rot_lp  # (B, T)

    # Mask then average per trajectory
    step_logp_masked = step_logp[mask]
    # Compute per-trajectory mean logp
    B = states.shape[0]
    traj_means = []
    start = 0
    for b in range(B):
        T = attention_mask[b].sum().item()
        if T > 0:
            traj_means.append(step_logp_masked[start:start+T].mean())
        else:
            traj_means.append(torch.tensor(0.0, device=states.device))
        start += T
    traj_means = torch.stack(traj_means, dim=0)  # (B,)

    # Weighted objective: maximize logπ => minimize negative
    loss = -(weights * traj_means).mean()
    return loss, {"policy_loss": loss.item()}


def main():
    import argparse
    ap = argparse.ArgumentParser(description="DT RL-style fine-tuning on clean expert trajectories")
    ap.add_argument("--data-root", type=str, default=r"E:\77777\my(1)\my\data",
                   help="Path to clean expert_traj folders")
    ap.add_argument("--grid-size", type=int, default=128)
    ap.add_argument("--margin", type=int, default=2)
    ap.add_argument("--placement-mode", type=str, choices=["layout", "heuristic"], default="layout")
    ap.add_argument("--epochs", type=int, default=10)
    ap.add_argument("--batch-size", type=int, default=8)
    ap.add_argument("--max-samples", type=int, default=None,
                   help="Maximum samples to use (None = use all available)")
    ap.add_argument("--train-split-ratio", type=float, default=0.95,
                   help="Ratio of data to use for training (rest for testing)")
    ap.add_argument("--device", type=str, default=("cuda" if torch.cuda.is_available() else "cpu"))
    ap.add_argument("--save-model", type=str, default="dt_clean_model.pth",
                   help="Path to save trained model")
    # Paper hyper-parameters
    ap.add_argument("--lambda1", type=float, default=1000.0)
    ap.add_argument("--lambda2", type=float, default=0.01)
    ap.add_argument("--alpha", type=float, default=1.0, help="sampling temperature for prioritized replay")
    ap.add_argument("--buffer-capacity", type=int, default=256)
    ap.add_argument("--fine-tune-iters", type=int, default=3, help="number of fine-tune cycles per epoch")
    ap.add_argument("--hpwl-threshold", type=float, default=None,
                   help="Soft HPWL threshold for overflow penalties (optional)")
    ap.add_argument("--slw-penalty-weight", type=float, default=DEFAULT_SLW_PENALTY_WEIGHT,
                   help="Weight applied when SLW increases (soft constraint penalty)")
    args = ap.parse_args()

    device = torch.device(args.device)
    data_root = Path(args.data_root)

    # Since data directory only contains clean trajectories, use all of them
    print(f"Using all trajectories from {data_root} (clean data only)")

    # Create dataset (data directory only contains clean trajectories)
    dataset = ExpertTrajectoryDataset(
        root_dir=data_root,
        split="train",  # Use all trajectories for training
        grid_size=args.grid_size,
        margin=args.margin,
        placement_mode=args.placement_mode,
        preload=False,
    )

    max_samples = args.max_samples if args.max_samples is not None else len(dataset)
    all_samples = collect_samples(dataset, max_samples=max_samples)
    print(f"Collected {len(all_samples)} usable clean expert trajectories")

    if len(all_samples) == 0:
        print("No valid samples found. Exiting.")
        return

    # Split into train and test sets
    import random
    random.seed(42)  # For reproducibility
    indices = list(range(len(all_samples)))
    random.shuffle(indices)
    
    train_size = int(len(all_samples) * args.train_split_ratio)
    train_indices = indices[:train_size]
    test_indices = indices[train_size:]
    
    train_samples = [all_samples[i] for i in train_indices]
    test_samples = [all_samples[i] for i in test_indices]
    
    print(f"Train set: {len(train_samples)} samples ({args.train_split_ratio*100:.1f}%)")
    print(f"Test set: {len(test_samples)} samples ({(1-args.train_split_ratio)*100:.1f}%)")

    # Use train_samples for training
    samples = train_samples

    model = DecisionTransformer(
        grid_size=args.grid_size,
        hidden_size=256,
        hi_dim=ExpertTrajectoryProcessor.HI_FEATURE_DIM,
    )
    model.to(device)

    optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4)

    epochs = args.epochs
    loss_history: List[float] = []
    reward_history: List[float] = []

    from collections import deque

    replay_buffer: deque = deque(maxlen=args.buffer_capacity)

    print(f"Starting training for {epochs} epochs with online policy rollouts...")

    for epoch in tqdm(range(epochs), desc="Training epochs"):
        epoch_losses: List[float] = []
        epoch_rewards: List[float] = []
        epoch_scores: List[float] = []
        epoch_hpwl: List[float] = []
        epoch_nslw: List[float] = []

        import random
        random.shuffle(train_indices)
        rollouts_collected = 0

        for sample_idx in train_indices:
            processor = dataset.get_processor(sample_idx)
            baseline_sample = train_samples[sample_idx] if sample_idx < len(train_samples) else None
            baseline_return = float(baseline_sample.returns_to_go[0].item()) if baseline_sample is not None else 0.0

            entry = rollout_policy(
                model=model,
                processor=processor,
                lambda1=args.lambda1,
                lambda2=args.lambda2,
                device=device,
                target_return=baseline_return,
                hpwl_threshold=args.hpwl_threshold,
                bonus_value=-0.01,
                slw_penalty_weight=args.slw_penalty_weight,
                deterministic=False,
            )

            if entry is None:
                continue

            placement_seq = entry.get("placement_sequence", [])
            if placement_seq and not satisfies_hard_constraints(processor, placement_seq, processor.grid_size, args.margin):
                continue

            replay_buffer.append(entry)
            epoch_rewards.append(entry["episode_reward"])
            epoch_scores.append(entry["score"])
            epoch_hpwl.append(entry.get("hpwl_final", 0.0))
            epoch_nslw.append(entry.get("nslw_final", 0.0))

            rollouts_collected += 1
            if rollouts_collected >= args.fine_tune_iters:
                break

        if replay_buffer:
            weights_full = prioritized_weights([buf_entry["score"] for buf_entry in replay_buffer], args.alpha)
            updates = min(args.fine_tune_iters, len(replay_buffer))

            for _ in range(updates):
                sample_size = min(args.batch_size, len(replay_buffer))
                chosen_indices = random.choices(range(len(replay_buffer)), weights=weights_full, k=sample_size)
                batch_entries = [replay_buffer[i] for i in chosen_indices]
                batch_weights = [weights_full[i] for i in chosen_indices]
                batch = build_training_batch(batch_entries, batch_weights)

                optimizer.zero_grad()
                loss, _ = policy_loss_from_buffer(batch, model, device)
                loss.backward()
                optimizer.step()
                epoch_losses.append(loss.item())

        avg_loss = float(np.mean(epoch_losses)) if epoch_losses else 0.0
        avg_reward = float(np.mean(epoch_rewards)) if epoch_rewards else 0.0
        avg_score = float(np.mean(epoch_scores)) if epoch_scores else 0.0
        avg_hpwl = float(np.mean(epoch_hpwl)) if epoch_hpwl else float("nan")
        avg_nslw = float(np.mean(epoch_nslw)) if epoch_nslw else float("nan")

        loss_history.append(avg_loss)
        reward_history.append(avg_reward)

        log_msg = (
            f"Epoch {epoch + 1}/{epochs} | Buffer: {len(replay_buffer)} | Loss: {avg_loss:.4f} "
            f"| Reward: {avg_reward:.4f} | Score: {avg_score:.4f}"
        )
        if not np.isnan(avg_hpwl):
            log_msg += f" | HPWL: {avg_hpwl:.2f} | NSLW: {avg_nslw:.4f}"
        print(log_msg)

    # Save the trained model
    torch.save(model.state_dict(), args.save_model)
    print(f"Model saved to {args.save_model}")

    # Evaluate (proxy): report average sample reward
    if len(test_samples) > 0:
        print(f"\nEvaluating on test set ({len(test_samples)} samples)...")
        model.eval()
        test_reward = 0.0
        test_count = 0
        with torch.no_grad():
            for sample in test_samples:
                rewards = sample.rewards if hasattr(sample, 'rewards') else None
                mask = sample.attention_mask.bool() if hasattr(sample, 'attention_mask') else None
                if rewards is not None and mask is not None and mask.any():
                    test_reward += rewards[mask].mean().item()
                    test_count += 1
        avg_test_reward = test_reward / max(test_count, 1)
        print(f"Test Reward (proxy): {avg_test_reward:.4f}")

    # Plot training curves
    plt.figure(figsize=(12, 4))

    plt.subplot(1, 3, 1)
    plt.plot(loss_history)
    plt.title('Training Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')

    plt.subplot(1, 3, 2)
    plt.plot(reward_history)
    plt.title('Average Reward')
    plt.xlabel('Epoch')
    plt.ylabel('Reward')

    plt.tight_layout()
    plt.savefig('training_curves_clean.png', dpi=150, bbox_inches='tight')
    print("Training curves saved to training_curves_clean.png")

    # Demo: Visualize one trajectory prediction
    if len(samples) > 0:
        print("\nGenerating demo visualization...")
        sample = samples[0]  # Use first sample for demo

        # Get processor for this trajectory
        processor = dataset._processor_cache.get(0)
        if processor is None:
            processor = dataset._load_processor(0)

        # Extract component info
        task_data = processor.task_data
        layout_data = processor.layout_data
        comp_id_to_size = {}
        for comp in task_data['components']:
            comp_id_to_size[comp['name']] = (comp['w'], comp['h'])

        # Build ground truth boxes from expert layout
        ground_truth_boxes = []
        for comp_name, comp_data in layout_data.items():
            x, y = comp_data['x'], comp_data['y']
            w, h = comp_id_to_size.get(comp_name, (1, 1))
            rot = comp_data.get('rot', 0)
            ground_truth_boxes.append((x, y, w, h, rot))

        # For demonstration, show the training sample's action sequence
        # This represents what the model was trained on
        sample_boxes = []
        component_sequence = list(layout_data.keys())  # Components in placement order

        # Convert sample actions to boxes (actions are x, y, rotation for each component)
        actions_list = sample.actions.tolist()
        for i, action in enumerate(actions_list):
            if i < len(component_sequence):
                comp_name = component_sequence[i]
                x, y, rot = action
                w, h = comp_id_to_size.get(comp_name, (5, 5))
                if int(rot) % 2 == 1:  # Rotate dimensions if needed
                    w, h = h, w
                sample_boxes.append((int(x), int(y), w, h, int(rot)))

        # Save board visualizations
        output_dir = Path('output')
        output_dir.mkdir(exist_ok=True)
        board_gt_path = output_dir / 'board_ground_truth_clean.png'
        board_sample_path = output_dir / 'board_training_sample_clean.png'
        _draw_board(ground_truth_boxes, args.grid_size, 'Ground Truth (Expert Layout)', board_gt_path)
        _draw_board(sample_boxes, args.grid_size, 'Training Sample Actions', board_sample_path)
        print(f"Saved board visuals to {board_gt_path} and {board_sample_path}")
        print(f"Ground truth has {len(ground_truth_boxes)} components")
        print(f"Training sample has {len(sample_boxes)} components")


if __name__ == "__main__":
    main()